<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1841" started-at="2018-01-11T11:32:51Z" finished-at="2018-01-11T11:32:53Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1841" started-at="2018-01-11T11:32:51Z" finished-at="2018-01-11T11:32:53Z">
      <class name="com.reqres.automation.testCases.TestGetRequests">
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.reqres.automation.testCases.TestGetRequests@647e447]" name="initialize" is-config="true" duration-ms="9" started-at="2018-01-11T17:02:51Z" finished-at="2018-01-11T17:02:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="getService()[pri:0, instance:com.reqres.automation.testCases.TestGetRequests@647e447]" name="getService" duration-ms="1812" started-at="2018-01-11T17:02:51Z" description="first test" finished-at="2018-01-11T17:02:53Z">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[JSONObject["data[1].last_name"] not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: JSONObject["data[1].last_name"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.reqres.automation.testCases.TestGetRequests.getService(TestGetRequests.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getService -->
      </class> <!-- com.reqres.automation.testCases.TestGetRequests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
